---
title: "strainct"
output: html_document
date: "2023-08-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is an exploration of missing strains in datsets.

```{r}
dirpath <- file.path("~", "founder_diet_study")
dirpath <- file.path(dirpath, "HarmonizedData")

traitSignal <- readRDS(file.path(dirpath, "traitSignal.rds"))
```

```{r}
tidyr::pivot_wider(
  dplyr::count( 
    dplyr::count(
      dplyr::distinct(traitSignal, 
                      .data$dataset, .data$trait, .data$strain),
      .data$dataset, .data$trait, name = "strains"),
    .data$dataset, .data$strains),
  names_from = "strains", values_from = "n", values_fill = 0)
```

```{r}
dplyr::summarize(
  dplyr::count( 
    dplyr::count(
      dplyr::distinct(traitSignal, 
                      .data$dataset, .data$trait, .data$strain),
      .data$dataset, .data$trait, name = "strains"),
    .data$dataset, .data$strains),
  n = sum(.data$n))
```

```{r}
dplyr::summarize(
  dplyr::filter(
  dplyr::count( 
    dplyr::count(
      dplyr::distinct(traitSignal, 
                      .data$dataset, .data$trait, .data$strain),
      .data$dataset, .data$trait, name = "strains"),
    .data$dataset, .data$strains),
  .data$dataset %in% c("Physio","LivMet","Lipid")),
  n = sum(.data$n))
```

# Liver RNA stats

```{r}
LivRnaStats <- readRDS(file.path(dirpath, "LivRna", "LivRnaStats.rds"))
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
ggplot(LivRnaStats %>% filter(term == "signal")) +
  aes(p.value) +
  geom_hline(yintercept = 1, col = "blue") +
  geom_vline(xintercept = 0.05, col = "blue") +
  geom_density()
```

```{r}
count(LivRnaStats %>% filter(term == "signal") %>% mutate(sig = p.value <= 0.05),
      sig)
```

# LivMet stats

```{r}
LivMetStats <- readRDS(file.path(dirpath, "LivMet", "LivMetStats.rds"))
```

```{r}
ggplot(LivMetStats %>% filter(term == "signal")) +
  aes(p.value) +
  geom_hline(yintercept = 1, col = "blue") +
  geom_vline(xintercept = 0.05, col = "blue") +
  geom_density()
```

```{r}
count(LivMetStats %>% filter(term == "signal") %>% mutate(sig = p.value <= 0.05),
      sig)
```

# Liver Met data.

```{r}
LivMetData <- readRDS(file.path(dirpath, "LivMet", "LivMetData.rds"))
```

```{r}
LivRnaData <- readRDS(file.path(dirpath, "LivRna", "LivRnaData.rds"))
```

LivMetStats has analysis as is. Now want to use `Pltp` as covariate.

```{r}
LivMetAncova <- foundr::traitAncova(LivMetData, LivMetStats,
                                    LivRnaData, "Pltp", "diet")
```

```{r}
summary_traitAncova(LivMetAncova, c("N-Hydroxy-IQ", "LAURATE"))
```

```{r}
ggplot_traitAncova(LivMetAncova, c("N-Hydroxy-IQ", "LAURATE"))
```

```{r}
LivMetAncova <- foundr::traitAncova(LivMetData, LivMetStats,
                                    LivRnaData, "Ugt1a1", "diet")
```

```{r}
summary_traitAncova(LivMetAncova, c("5-L-Glutamyl-taurine", "Neamine"))
```

```{r}
ggplot_traitAncova(LivMetAncova, c("5-L-Glutamyl-taurine", "Neamine"))
```

# Liver RNA data.


```{r}
LivRnaData <- readRDS(file.path(dirpath, "LivRna", "LivRnaData.rds"))
```

```{r}
  dplyr::mutate(
  dplyr::count(
  dplyr::filter(
    dplyr::count(
      dplyr::distinct(LivRnaData, 
                      .data$trait, .data$strain),
      .data$trait, name = "strains"),
    .data$strains <= 8),
  .data$strains, name = "count"),
  percent = signif(100 * count / sum(count), 4))
```

```{r}
LivRnaSignal <- readRDS(file.path(dirpath, "../LivRna", "LivRnaSignal.rds"))
```

```{r}
  dplyr::mutate(
  dplyr::count(
  dplyr::filter(
    dplyr::count(
      dplyr::distinct(LivRnaSignal, 
                      .data$trait, .data$strain),
      .data$trait, name = "strains"),
    .data$strains <= 8),
  .data$strains, name = "count"),
  percent = signif(100 * count / sum(count), 4))
```

```{r}
keepTraits <- dplyr::filter(
    dplyr::count(
      dplyr::distinct(LivRnaSignal, 
                      .data$trait, .data$strain),
      .data$trait, name = "strains"),
    .data$strains >= max(.data$strains) - 2)$trait
```

```{r}
length(keepTraits)
```

## Reduce LivRna data and save


```{r}
dataset <- file.path(dirpath, "../LivRna")

  LivRnaStats <- 
    dplyr::filter(
      LivRnaStats,
      .data$trait %in% keepTraits)
  
  saveRDS(LivRnaStats, file.path(dataset, paste0(dataset, "Stats.rds")))
  
  LivRnaData <-
    dplyr::filter(
      LivRnaData,
      .data$trait %in% keepTraits)
  saveRDS(LivRnaData, file.path(dataset, paste0(dataset, "Data.rds")))
  
  LivRnaSignal <- 
    dplyr::filter(
      LivRnaSignal,
      .data$trait %in% keepTraits)
  saveRDS(LivRnaSignal, file.path(dataset, paste0(dataset, "Signal.rds")))
```

